### ISSUE TITLE
Why is it so difficult to install? 

### ISSUE THREAD

**Issue by bemoregt** [javiribera/peterpy#1]
HI, @javiribera 

I met this error when install peterpy.

'ERROR: Package 'peterpy' requires a different Python: 3.7.6 not in '>=3.3, <=3.7'
when install at python3.7.6.

and also error happen when install at python3.6.x .
and also error happen when install at python3.8.x .

Why is it so difficult to install?  - -;

Thanks.
Best,
@bemoregt.

**Comment by javiribera** [comment]
I just installed it with "Python 3.6.12 :: Anaconda, Inc." and yielded no such error, what python version are you running exactly? Please provide the output of `python -V`.

Python 3.8 is not supported [as it says here](https://github.com/javiribera/peterpy/blob/master/setup.py#L35) because I have never tried it with it. Python 3.8 wasn't released yet when I released peterpy. If you think peterpy could work with Python 3.8 feel free to modify that line and install it. PRs are welcomed.

**Comment by javiribera** [comment]
facc4a00139943a51b43fdf845cae2f36c8d6ca4 just made it compatible with Python 3.5-3.9. This is now in peterpy 1.1.0. Feel free to reopen the issue if the problem persists.
